---
- hosts: ios_devices
  gather_facts: yes
  connection: local
  vars: 
    - filename_timestamp: "{{ansible_date_time.year}}{{ansible_date_time.month}}{{ansible_date_time.day}}{{ansible_date_time.hour}}{{ansible_date_time.minute}}{{ansible_date_time.second}}{{ansible_date_time.tz}}"

  tasks:

  - name: IDENTIFY | Verify target switches
    set_fact:
      provider:
        host: "{{ inventory_hostname }}" 
        username: "{{ ansible_user }}"
        password: "{{ ansible_pass }}"

  - name: IOS | Execute IOS commands for IOS devices , doing show inventory
    ios_command:
      provider: "{{ provider }}"
      commands:
        - show run
    register: config

  - name: save | output of running configs to /etc/ansible/clock-signal-devs
    copy:
      content: "{{ config.stdout[0] }}"
      dest: "/etc/ansible/clock-signal-devs/show_inv_{{ inventory_hostname }}_{{ filename_timestamp }}.txt"
